source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Attension' do
    pod 'RealmSwift', '0.98.7'
    pod 'BlocksKit'
    pod 'SwiftTask'
    pod 'INTULocationManager'
    pod 'R.swift'
    pod 'Himotoki'
    pod 'Firebase'
end
