source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Attention' do
    pod 'RealmSwift'
    pod 'BlocksKit'
    pod 'SwiftTask'
    pod 'INTULocationManager'
    pod 'R.swift'
    pod 'Himotoki'
    pod 'Firebase'
    pod 'Bond'
    pod 'SVProgressHUD'
    pod 'Fabric'
    pod 'Crashlytics'
end

target 'AttentionTests' do
    pod 'RealmSwift'
    pod 'BlocksKit'
    pod 'SwiftTask'
    pod 'INTULocationManager'
    pod 'R.swift'
    pod 'Himotoki'
    pod 'Firebase'
    pod 'Bond'
    pod 'SVProgressHUD'
    pod 'Fabric'
    pod 'Crashlytics'
end

post_install do | installer |
require 'fileutils'

FileUtils.cp_r('Pods/Target Support Files/Pods-Attention/Pods-Attention-acknowledgements.plist', 'Settings.bundle/Acknowledgements.plist', :remove_destination => true)

# エラー
#FileUtils.cp_r('Pods/Pods-acknowledgements.plist', 'TESTSettings/Settings.bundle/Acknowledgements.plist', :remove_destination => true)

end
